name: abdul_ai_chatbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  googleapis_auth: ^1.4.0
  http: ^1.2.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/dialogflow_key.json
