// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTFG_cy9mlLR5woq235XFnHR2qeEaZZC0',
    appId: '1:698451314467:web:291224e108137aaf91ae96',
    messagingSenderId: '698451314467',
    projectId: 'abdul-chatbot',
    authDomain: 'abdul-chatbot.firebaseapp.com',
    storageBucket: 'abdul-chatbot.firebasestorage.app',
    measurementId: 'G-YXEKCLV4P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZR2jlLNxDsMLJveQ02OfjIwW5wksGMFw',
    appId: '1:698451314467:android:cdba4e0975688b5991ae96',
    messagingSenderId: '698451314467',
    projectId: 'abdul-chatbot',
    storageBucket: 'abdul-chatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQSMbM3xrIoVlhTD0ZvlCNVWUDfGW6I8',
    appId: '1:698451314467:ios:cb9b1aaf55006a4b91ae96',
    messagingSenderId: '698451314467',
    projectId: 'abdul-chatbot',
    storageBucket: 'abdul-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.abdulAiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQSMbM3xrIoVlhTD0ZvlCNVWUDfGW6I8',
    appId: '1:698451314467:ios:cb9b1aaf55006a4b91ae96',
    messagingSenderId: '698451314467',
    projectId: 'abdul-chatbot',
    storageBucket: 'abdul-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.abdulAiChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTFG_cy9mlLR5woq235XFnHR2qeEaZZC0',
    appId: '1:698451314467:web:ab9b3f4f6fd0c69c91ae96',
    messagingSenderId: '698451314467',
    projectId: 'abdul-chatbot',
    authDomain: 'abdul-chatbot.firebaseapp.com',
    storageBucket: 'abdul-chatbot.firebasestorage.app',
    measurementId: 'G-K8P8V0SL69',
  );
}
